class SubCategory < ApplicationRecord
  include ActiveHash::Associations
  belongs_to :main_category

  self.data = [
    {id: 1, sub_category: "洗顔フォーム", main_category_id: 1 },
    {id: 2, sub_category: "クレンジング", main_category_id: 1 },
    {id: 3, sub_category: "日焼け止め（顔用）", main_category_id: 1 },
    {id: 4, sub_category: "ローション（化粧水）", main_category_id: 1 },
    {id: 5, sub_category: "乳液", main_category_id: 1 },
    {id: 6, sub_category: "セラム（美容液）", main_category_id: 1 },
    {id: 7, sub_category: "保湿クリーム", main_category_id: 1 },
    {id: 8, sub_category: "その他", main_category_id: 1 },
    {id: 9, sub_category: "ファンデーション", main_category_id: 2 },
    {id: 10, sub_category: "コンシーラー", main_category_id: 2 },
    {id: 11, sub_category: "フェイスパウダー", main_category_id: 2 },
    {id: 12, sub_category: "ハイライト・シェーディング", main_category_id: 2 },
    {id: 13, sub_category: "化粧下地", main_category_id: 2 },
    {id: 14, sub_category: "その他", main_category_id: 2 },
    {id: 15, sub_category: "アイシャドウ", main_category_id: 3 },
    {id: 16, sub_category: "アイライナー", main_category_id: 3 },
    {id: 17, sub_category: "アイベース", main_category_id: 3 },
    {id: 18, sub_category: "マスカラ", main_category_id: 3 },
    {id: 19, sub_category: "アイブロウ", main_category_id: 3 },
    {id: 20, sub_category: "マスカラ", main_category_id: 3 },
    {id: 21, sub_category: "リップ", main_category_id: 3 },
    {id: 22, sub_category: "チーク", main_category_id: 3 },
    {id: 23, sub_category: "カラコン", main_category_id: 3 },
    {id: 24, sub_category: "その他", main_category_id: 3 },
    {id: 25, sub_category: "ボディークリーム", main_category_id: 4 },
    {id: 26, sub_category: "日焼け止め（体用）", main_category_id: 4 },
    {id: 27, sub_category: "シャンプー・コンディショナー", main_category_id: 4 },
    {id: 28, sub_category: "除毛クリーム", main_category_id: 4 },
    {id: 29, sub_category: "ボディミスト", main_category_id: 5 },
    {id: 30, sub_category: "香水", main_category_id: 5 },
    {id: 31, sub_category: "柔軟剤", main_category_id: 5 },
    {id: 32, sub_category: "その他", main_category_id: 5 },
    {id: 33, sub_category: "美顔器", main_category_id: 6 },
    {id: 34, sub_category: "保湿スチーマー", main_category_id: 6 },
    {id: 35, sub_category: "その他", main_category_id: 6 },
    {id: 36, sub_category: "脱毛", main_category_id: 7 },
    {id: 37, sub_category: "美容ハイフ", main_category_id: 7 },
    {id: 38, sub_category: "整形", main_category_id: 7 },
    {id: 39, sub_category: "ホワイトニング", main_category_id: 7 },
    {id: 40, sub_category: "シワ・たるみ改善・シミ取り・肌質改善", main_category_id: 7 },
    {id: 41, sub_category: "その他", main_category_id: 7 },
    {id: 42, sub_category: "その他", main_category_id: 8 },
  ]

end
